### ISSUE TITLE
stats flickering when downloading multiple torrents

### ISSUE THREAD

**Issue by noughtmare** [proninyaroslav/libretorrent#70] opened 2017-02-01 23:28 UTC
See this gif:

![problem](https://cloud.githubusercontent.com/assets/2665074/22530903/3d8248b6-e8de-11e6-8538-95b6e5d55dbd.gif)

This only happens when multiple torrents are downloading.

This is version 1.2 from fdroid.

**Comment by proninyaroslav** [comment] 2017-02-02 16:12
Hello. I can not say what the problem is, check it out after release 1.3, I will correct and revise some things.

**Comment by comradekingu** [comment] 2017-04-23 04:33
Looks to be happening as a result of double digit download speeds, thus adding a line-shift to "(1%)" for however long it lasts.

**Comment by noughtmare** [comment] 2017-04-23 09:49
Its not only the wrapping of the download speed that's an issue. The main problem is that it flickers between the stats of multiple active torrents. In the gif you can see that for example the progress bar also flickers between about 5% and 0%.

**Comment by proninyaroslav** [comment] 2017-04-23 09:53
@noughtmare 
Does this happen to all torrents? Can you test it on another device? I could not reproduce this problem.

**Comment by noughtmare** [comment] 2017-04-23 22:48
It happens as soon as more than one torrent is downloading with every torrent I tried. I don't have another device I can test this on.

**Comment by proninyaroslav** [comment] 2017-07-07 18:02
Due with 1.4 release, I close this issue, but if this problem appears again, let me know.

**Closed by proninyaroslav** 2017-07-07 18:02 UTC
