### ISSUE TITLE
java.lang.NoSuchMethodError: no static method 

### ISSUE THREAD

**Issue by e4basil** [proninyaroslav/libretorrent#157] opened 2018-02-01 06:46 UTC
```
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.5
BRAND=Xiaomi
PHONE_MODEL=Redmi Note 3
CUSTOM_DATA=
STACK_TRACE=java.lang.NoSuchMethodError: no static method "Lcom/frostwire/jlibtorrent/swig/libtorrent_jni;.SwigDirector_alert_notify_callback_on_alert(Lcom/frostwire/jlibtorrent/swig/alert_notify_callback;)V"
at com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init(Native Method)
at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:3145)
at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_error_notification_get(Native Method)
at com.frostwire.jlibtorrent.swig.e.<clinit>(alert.java:493)
at com.frostwire.jlibtorrent.a.d.<clinit>(AlertType.java:11)
at com.frostwire.jlibtorrent.q.<clinit>(SessionManager.java:23)
at org.proninyaroslav.libretorrent.services.TorrentTaskService.onCreate(TorrentTaskService.java:217)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2910)
at android.app.ActivityThread.access$2000(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:5527)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by proninyaroslav** [comment] 2018-02-01 07:57
Strange error. Under what circumstances did it occur? Was it repeated again?

**Comment by e4basil** [comment] 2018-02-01 13:30
I think I accidentally added `minifyEnabled true` in gradle file

**Comment by proninyaroslav** [comment] 2018-02-01 14:17
I.e did you build app from the source yourself?

**Comment by e4basil** [comment] 2018-02-01 14:30
yes

**Comment by e4basil** [comment] 2018-02-01 14:33
I changed `minifyEnabled true` to `false ` and successfully build

**Comment by proninyaroslav** [comment] 2018-02-01 14:40
I don't use code obfuscation and can't guarantee its working after obfuscation. In addition, the problem is rather in `jlibtorrent`.

**Comment by proninyaroslav** [comment] 2018-02-03 17:23
I think it's worth closing issue until clarifying its cause on the side of `jlibtorrent`.

**Closed by proninyaroslav** 2018-02-03 17:23 UTC
